package main

import (
	"bytes"
	"encoding/binary"
	"encoding/xml"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"io"
	"math"
	"os"
	"runtime"
	"strings"
	"unicode"

	"seedhammer.com/bezier"
	"seedhammer.com/bspline"
	"seedhammer.com/font/vector"
	"seedhammer.com/svgpath"
)

var (
	packageName = flag.String("package", "main", "package name")
	scale       = flag.Int("scale", 1, "scale font")
	precision   = flag.Int("prec", 16, "sampling precision")
	dump        = flag.String("dump", "", "dump to SVG")
	splice      = flag.Bool("splice", false, "spline lines to curve segments")
)

type Face struct {
	Metrics vector.Metrics
	// Index maps a character to its segment range.
	Index [unicode.MaxASCII]vector.Glyph
	// Spline knots encoded as line byte(0 or 1), int16(x-coord), int16(y-coord).
	Splines []byte
}

func main() {
	flag.Parse()

	if flag.NArg() != 2 {
		fmt.Fprintf(os.Stderr, "usage: convert infile outfile\n")
		os.Exit(1)
	}

	infile, name := flag.Arg(0), flag.Arg(1)
	if err := run(infile, name); err != nil {
		fmt.Fprintf(os.Stderr, "%s: %v\n", infile, err)
		os.Exit(1)
	}
}

func run(infile, name string) error {
	in, err := os.ReadFile(infile)
	if err != nil {
	}
	conv, runeToSegs, err := convert(in)
	if err != nil {
		return err
	}
	samples, err := buildBSplines(conv, runeToSegs)
	if err != nil {
		return err
	}
	gosrc, data, err := generate(name, conv)
	if err != nil {
		return err
	}
	if err := os.WriteFile(name+".go", gosrc, 0o600); err != nil {
		return err
	}
	if err := os.WriteFile(name+".bin", data, 0o600); err != nil {
		return err
	}
	if f := *dump; f != "" {
		svg := dumpSVG(vector.NewFace(data), samples)
		if err := os.WriteFile(f, svg, 0o600); err != nil {
			return err
		}
	}
	return nil
}

func buildBSplines(f *Face, runeToSegs map[rune][]svgpath.Segment) (samples map[rune][]bezier.Point, err error) {
	// Spline optimization is slow, so smear out the work across
	// available CPUs.
	var index [unicode.MaxASCII][]byte
	type job struct {
		r    rune
		segs []svgpath.Segment
	}
	type result struct {
		r       rune
		samples []bezier.Point
		spline  []byte
		err     error
	}
	samples = make(map[rune][]bezier.Point)
	jobs := make(chan job)
	res := make(chan result, len(runeToSegs))
	defer close(res)
	prec := max(1, f.Metrics.Height/(*precision))
	for range runtime.NumCPU() {
		go func() {
			for {
				j, ok := <-jobs
				if !ok {
					return
				}
				s, spline, err := svgpath.ToBSpline(j.segs, prec, *splice)
				res <- result{j.r, s, encodeBSpline(spline), err}
			}
		}()
	}
	for r, segs := range runeToSegs {
		jobs <- job{r, segs}
	}
	for range cap(res) {
		r := <-res
		if err := r.err; err != nil {
			return nil, fmt.Errorf("%q: %w", string(r.r), err)
		}
		samples[r.r] = r.samples
		index[r.r] = r.spline
	}
	for r, spline := range index {
		if len(spline) == 0 {
			continue
		}
		f.Index[r].Start = len(f.Splines)
		f.Splines = append(f.Splines, spline...)
		f.Index[r].End = len(f.Splines)
	}
	return samples, nil
}

func encodeBSpline(spline []vector.Knot) []byte {
	knots := make([]byte, 0, len(spline)*vector.IndexElemSize)
	for _, k := range spline {
		l := byte(0)
		if k.Line {
			l = 1
		}
		x, y := int16(k.Ctrl.X), int16(k.Ctrl.Y)
		if int(x) != k.Ctrl.X || int(y) != k.Ctrl.Y {
			panic(fmt.Errorf("spline knot coordinates out of range: %v", k.Ctrl))
		}
		knots = append(knots, l)
		knots = bo.AppendUint16(knots, uint16(x))
		knots = bo.AppendUint16(knots, uint16(y))
	}
	return knots
}

var bo = binary.LittleEndian

func generate(name string, conv *Face) (gosrc []byte, data []byte, err error) {
	var output bytes.Buffer
	fmt.Fprintf(&output, "// Code generated by seedhammer.com/cmd/vectorfont; DO NOT EDIT.\npackage %s\n", *packageName)
	fmt.Fprintf(&output, "import (\n")
	fmt.Fprintf(&output, "    _ \"embed\"\n")
	fmt.Fprintf(&output, "    \"unsafe\"\n")
	fmt.Fprintf(&output, "    \"seedhammer.com/font/vector\"\n")
	fmt.Fprintf(&output, ")\n\n")
	fmt.Fprintf(&output, "var Font = vector.NewFace(unsafe.Slice(unsafe.StringData(%sData), len(%[1]sData)))\n\n", name)
	fmt.Fprintf(&output, "//go:embed %s.bin\n", name)
	fmt.Fprintf(&output, "var %sData string\n", name)
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, nil, err
	}

	ascent := uint16(conv.Metrics.Ascent)
	if int(ascent) != conv.Metrics.Ascent {
		return nil, nil, errors.New("ascent overflows uint16")
	}
	height := uint16(conv.Metrics.Height)
	if int(height) != conv.Metrics.Height {
		return nil, nil, errors.New("height overflows uint16")
	}
	data = bo.AppendUint16(data, ascent)
	data = bo.AppendUint16(data, height)
	for _, g := range conv.Index {
		adv := uint16(g.Advance)
		if int(adv) != g.Advance {
			return nil, nil, errors.New("advance overflows")
		}
		data = bo.AppendUint16(data, adv)
		start, end := g.Start+vector.OffSplines, g.End+vector.OffSplines
		s16, e16 := uint16(start), uint16(end)
		if int(s16) != start || int(e16) != end {
			return nil, nil, errors.New("spline offset overflows uint16")
		}
		data = bo.AppendUint16(data, s16)
		data = bo.AppendUint16(data, e16)
	}
	if len(data) != vector.OffSplines {
		panic("miscalculated spline offset")
	}
	data = append(data, conv.Splines...)
	return formatted, data, nil
}

type MetaData struct {
	Advance, Height, Baseline int
}

func convert(svg []byte) (*Face, map[rune][]svgpath.Segment, error) {
	d := xml.NewDecoder(bytes.NewReader(svg))
	for {
		root, err := d.Token()
		if err != nil {
			return nil, nil, err
		}
		t, ok := root.(xml.StartElement)
		if !ok {
			continue
		}
		if !ok || t.Name.Local != "svg" {
			return nil, nil, errors.New("missing <svg> root element")
		}
		face := new(Face)
		meta, err := parseMeta(svg)
		if err != nil {
			return nil, nil, err
		}
		face.Metrics.Ascent = meta.Baseline
		face.Metrics.Height = meta.Height
		face.Index[' '] = vector.Glyph{
			Advance: meta.Advance,
		}
		chars, err := parseChars(face, d, meta.Advance, meta.Baseline)
		return face, chars, err
	}
}

func parseMeta(data []byte) (*MetaData, error) {
	type Line struct {
		ID string  `xml:"id,attr"`
		X1 float64 `xml:"x1,attr"`
		Y1 float64 `xml:"y1,attr"`
		X2 float64 `xml:"x2,attr"`
		Y2 float64 `xml:"y2,attr"`
	}
	type SVG struct {
		XMLName xml.Name `xml:"svg"`
		Lines   []Line   `xml:"line"`
	}
	var svg SVG
	if err := xml.Unmarshal(data, &svg); err != nil {
		return nil, err
	}
	var meta MetaData
	for _, line := range svg.Lines {
		switch line.ID {
		case "advance":
			meta.Advance = mustInt(line.X2 - line.X1)
		case "height":
			meta.Height = mustInt(line.Y2 - line.Y1)
		case "baseline":
			meta.Baseline = mustInt(line.Y1)
		}
	}
	return &meta, nil
}

func findAttr(e xml.StartElement, name string) (string, bool) {
	for _, a := range e.Attr {
		if a.Name.Local == name {
			return a.Value, true
		}
	}
	return "", false
}

func mustInt(v float64) int {
	sf := float64(*scale)
	return int(math.Round(v * sf))
}

func parseChars(face *Face, d *xml.Decoder, adv, ascent int) (map[rune][]svgpath.Segment, error) {
	offx := 0
	runeToSegs := make(map[rune][]svgpath.Segment)
	for {
		t, err := d.Token()
		if err != nil {
			if err != io.EOF {
				return nil, err
			}
			break
		}
		e, ok := t.(xml.StartElement)
		if !ok {
			continue
		}
		switch e.Name.Local {
		case "style":
			if err := d.Skip(); err != nil {
				return nil, err
			}
			continue
		}
		id, _ := findAttr(e, "id")
		switch id {
		case "advance", "height", "baseline", "size":
			// Skip anonymous and meta-data elements.
			if err := d.Skip(); err != nil {
				return nil, err
			}
			continue
		}
		r, ok := mapChar(id)
		if !ok {
			return nil, fmt.Errorf("unknown character id: %q", id)
		}
		segs, err := parseSegments(face, d, e, offx, -ascent, nil)
		if err != nil {
			return nil, err
		}
		if segs2 := svgpath.Optimize(segs); len(segs2) > 0 {
			runeToSegs[r] = segs2
		}
		face.Index[r] = vector.Glyph{
			Advance: adv,
		}
		offx -= adv
	}
	return runeToSegs, nil
}

func parseSegments(face *Face, d *xml.Decoder, e xml.StartElement, offx, offy int, segs []svgpath.Segment) ([]svgpath.Segment, error) {
	encode := func(op svgpath.SegmentOp, args ...bezier.Point) {
		seg := svgpath.Segment{Op: op}
		if len(args) > len(seg.Args) {
			panic("too many arguments")
		}
		copy(seg.Args[:], args)
		segs = append(segs, seg)
	}
	switch n := e.Name.Local; n {
	case "g":
		for {
			t, err := d.Token()
			if err != nil {
				return segs, err
			}
			switch t := t.(type) {
			case xml.StartElement:
				segs, err = parseSegments(face, d, t, offx, offy, segs)
				if err != nil {
					return segs, err
				}
			case xml.EndElement:
				return segs, nil
			}
		}
	case "line":
		var line struct {
			X1 float64 `xml:"x1,attr"`
			Y1 float64 `xml:"y1,attr"`
			X2 float64 `xml:"x2,attr"`
			Y2 float64 `xml:"y2,attr"`
		}
		if err := d.DecodeElement(&line, &e); err != nil {
			return segs, err
		}
		encode(svgpath.MoveTo, bezier.Pt(mustInt(line.X1)+offx, mustInt(line.Y1)+offy))
		encode(svgpath.LineTo, bezier.Pt(mustInt(line.X2)+offx, mustInt(line.Y2)+offy))
		return segs, nil
	case "polyline":
		points, ok := findAttr(e, "points")
		if !ok {
			return segs, errors.New("missing points attribute for <polyline>")
		}
		points = strings.TrimSpace(points)
		coords := strings.Split(points, " ")
		for i, c := range coords {
			var x, y float64
			if _, err := fmt.Sscanf(c, "%f,%f", &x, &y); err != nil {
				return segs, fmt.Errorf("invalid coordinates %q in <polyline>:", c)
			}
			op := svgpath.LineTo
			if i == 0 {
				op = svgpath.MoveTo
			}
			encode(op, bezier.Pt(mustInt(x)+offx, mustInt(y)+offy))
		}
		return segs, d.Skip()
	case "path":
		cmds, ok := findAttr(e, "d")
		if !ok {
			return segs, errors.New("missing d attribute for <path>")
		}
		psegs, err := svgpath.ParseData(cmds, offx, offy, mustInt)
		segs = append(segs, psegs...)
		if err != nil {
			return segs, err
		}
		return segs, d.Skip()
	default:
		return segs, fmt.Errorf("unsupported element: <%s>", n)
	}
}

func mapChar(id string) (rune, bool) {
	var r rune
	switch {
	case len(id) == 1:
		r = rune(id[0])
	default:
		switch id {
		case "zero":
			r = '0'
		case "one":
			r = '1'
		case "two":
			r = '2'
		case "three":
			r = '3'
		case "four":
			r = '4'
		case "five":
			r = '5'
		case "six":
			r = '6'
		case "seven":
			r = '7'
		case "eight":
			r = '8'
		case "nine":
			r = '9'
		case "colon":
			r = ':'
		case "semicolon":
			r = ';'
		case "comma":
			r = ','
		case "slash":
			r = '/'
		case "apostrophe":
			r = '\''
		case "dash":
			r = '-'
		case "period":
			r = '.'
		case "leftparen":
			r = '('
		case "rightparen":
			r = ')'
		case "leftbracket":
			r = '['
		case "rightbracket":
			r = ']'
		case "leftcurlybrace":
			r = '{'
		case "rightcurlybrace":
			r = '}'
		case "hash":
			r = '#'
		case "star":
			r = '*'
		case "at":
			r = '@'
		case "lt":
			r = '<'
		case "gt":
			r = '>'
		default:
			return 0, false
		}
	}
	return r, true
}

func expandUniformBSpline(spline vector.UniformBSpline) []bspline.Knot {
	var knots []bspline.Knot
	var last bezier.Point
	for {
		c, ok := spline.Next()
		if !ok {
			break
		}
		t := uint(1)
		if c.Ctrl == last {
			t = 0
		}
		last = c.Ctrl
		k := bspline.Knot{
			Engrave: c.Line,
			Ctrl:    c.Ctrl,
			T:       t,
		}
		knots = append(knots, k)
	}
	return knots
}

func dumpSVG(f *vector.Face, samples map[rune][]bezier.Point) []byte {
	out := new(bytes.Buffer)

	var alphabet []rune
	width := 0
	for r := range rune(unicode.MaxASCII) {
		if adv, _, ok := f.Decode(r); ok {
			alphabet = append(alphabet, r)
			width += adv
		}
	}
	const margin = 20
	m := f.Metrics()
	w, h := width+2*margin, m.Height+2*margin
	aspect := w / h
	fmt.Fprintf(out, "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"%d %d %d %d\" width=\"%d\" height=\"%d\">\n",
		-margin, -m.Ascent-margin, w, h, 200*aspect, 200)

	fmt.Fprintf(out, `<defs><style>
		.spline { fill: none; stroke: #0984e3; stroke-width: %g; stroke-linecap: round; }
	</style></defs>`, float64(m.Height)/100)
	x := 0
	fmt.Fprint(out, `<path class="spline" d="`)
	type circle struct {
		pos    bezier.Point
		fill   string
		radius float64
	}
	var circles []circle
	for _, r := range alphabet {
		for _, s := range samples[r] {
			c := s.Add(bezier.Pt(x, 0))
			circles = append(circles, circle{c, "black", 1.5})
		}
		adv, uspline, _ := f.Decode(r)
		spline := expandUniformBSpline(uspline)

		var seg bspline.Segment
		first := true
		for _, k := range spline {
			c, dt, line := seg.Knot(k)
			if dt == 0 {
				continue
			}
			circles = append(circles, circle{k.Ctrl.Add(bezier.Pt(x, 0)), "blue", 1.2})
			c = c.Add(bezier.Pt(x, 0))
			if line {
				if first {
					first = false
					circles = append(circles, circle{c.C0, "red", 1})
				}
				circles = append(circles, circle{c.C3, "red", 1})
				fmt.Fprintf(out, " C %d %d, %d %d, %d %d",
					c.C1.X, c.C1.Y, c.C2.X, c.C2.Y, c.C3.X, c.C3.Y)
			} else {
				first = true
				fmt.Fprintf(out, " M %d %d", c.C3.X, c.C3.Y)
			}
		}

		x += adv
	}
	fmt.Fprintln(out, `" />`)
	for _, c := range circles {
		fmt.Fprintf(out, `<circle cx="%d" cy="%d" r="%g" fill="%s"/>`, c.pos.X, c.pos.Y, float64(m.Height)/200*c.radius, c.fill)
	}
	fmt.Fprintln(out, "</svg>")
	return out.Bytes()
}
