// Command textplate generates the glyph geometry and plate grid data
// for the text plate editor (index.html) and the NFC writer CLI
// (write-nfc.py). The output is derived from the same packages the
// firmware engraves with, so composition tools match the engraved
// plate exactly.
//
// Usage:
//
//	go run seedhammer.com/cmd/textplate cmd/textplate/glyphs.js
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"seedhammer.com/backup"
	"seedhammer.com/curves"
	"seedhammer.com/engrave"
	"seedhammer.com/font/glyph"
	"seedhammer.com/font/sh"
	"seedhammer.com/nfc/type4"
)

// The SH2 engraver parameters, as in cmd/controller/platform_sh2.go.
const mm = 200 / 8 * 256

var conf = engrave.StepperConfig{
	TicksPerSecond: 30 * mm,
	Speed:          30 * mm,
	EngravingSpeed: 8 * mm,
	Acceleration:   250 * mm,
	Jerk:           2600 * mm,
}

var params = engrave.Params{
	StrokeWidth:   int(0.3 * mm),
	Millimeter:    mm,
	StepperConfig: conf,
}

// plateFontSizes mirrors the gui ladder.
var plateFontSizes = []float32{3.8, 3.4, 3.0}

type sizeEntry struct {
	MM   float32 `json:"mm"`
	Cols int     `json:"cols"`
	Rows int     `json:"rows"`
}

type fontData struct {
	Height   int               `json:"height"`
	Ascent   int               `json:"ascent"`
	Advance  int               `json:"advance"`
	PlateMM  int               `json:"plateMM"`
	MarginMM int               `json:"marginMM"`
	StrokeMM float32           `json:"strokeMM"`
	Sizes    []sizeEntry       `json:"sizes"`
	Glyphs   map[string]string `json:"glyphs"`

	// The seedhammer.com:curves record parameters, for compiling
	// compositions to vector payloads.
	RecordType string `json:"recordType"`
	Version    int    `json:"version"`
	PayloadCap int    `json:"payloadCap"`

	// Drawing caps the device enforces, single-sourced from the curves
	// package so the editor's gauges cannot drift from the firmware.
	MaxStrokes int `json:"maxStrokes"`
	MaxMinutes int `json:"maxMinutes"`
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: textplate <output.js>")
		os.Exit(1)
	}
	m := sh.Font.Metrics()
	adv, _, ok := sh.Font.Decode('W')
	if !ok {
		panic("W not in font")
	}
	data := fontData{
		Height:   m.Height,
		Ascent:   m.Ascent,
		Advance:  adv,
		PlateMM:  85,
		MarginMM: 3,
		StrokeMM: 0.3,
		Glyphs:   make(map[string]string),

		RecordType: curves.RecordType,
		Version:    curves.Version,
		// The NDEF file cap, minus record framing headroom.
		PayloadCap: type4.NDEFFileSize - 64,

		MaxStrokes: curves.MaxStrokes,
		MaxMinutes: curves.MaxMinutes,
	}
	for _, size := range plateFontSizes {
		data.Sizes = append(data.Sizes, sizeEntry{
			MM:   size,
			Cols: backup.CharsPerLine(params, sh.Font, size),
			Rows: backup.LinesPerPlate(params, size),
		})
	}
	for ch := rune(0); ch < 128; ch++ {
		if _, _, ok := sh.Font.Decode(ch); !ok {
			continue
		}
		data.Glyphs[string(ch)] = glyphPath(ch)
	}
	enc, err := json.MarshalIndent(data, "", "\t")
	if err != nil {
		panic(err)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by \"go run seedhammer.com/cmd/textplate\"; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "//\n// Glyph paths are in font units with the baseline at y=%d. The\n", m.Ascent)
	fmt.Fprintf(&b, "// value is strict JSON so non-JS tools can parse it too.\n")
	fmt.Fprintf(&b, "const SH = %s;\n", enc)
	if err := os.WriteFile(os.Args[1], []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// glyphPath returns a glyph's strokes as SVG path commands in font
// units. The path is pure geometry from the font spline, without the
// planner's travel and acceleration knots, so it doubles as the
// glyph's curves payload fragment. It comes from font/glyph, the same
// source the engraving converter uses, so the two never diverge.
func glyphPath(ch rune) string {
	if _, _, ok := sh.Font.Decode(ch); !ok {
		panic("glyph not in font")
	}
	return glyph.Path(ch)
}
