package bbqr

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"math/rand"
	"os"
	"slices"
	"strings"
	"testing"
)

type vector struct {
	Name        string `json:"name"`
	DataHex     string `json:"data_hex"`
	FileType    string `json:"file_type"`
	EncodingOpt string `json:"encoding_opt"`
	Opts        struct {
		MinVersion int `json:"min_version"`
		MaxVersion int `json:"max_version"`
		MinSplit   int `json:"min_split"`
		MaxSplit   int `json:"max_split"`
	} `json:"opts"`
	Version  int      `json:"version"`
	Encoding string   `json:"encoding"`
	Parts    []string `json:"parts"`
}

type vectorFile struct {
	VersionChars []int    `json:"version_chars"`
	Vectors      []vector `json:"vectors"`
}

func loadVectors(t *testing.T) vectorFile {
	t.Helper()
	raw, err := os.ReadFile("testdata/vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var vf vectorFile
	if err := json.Unmarshal(raw, &vf); err != nil {
		t.Fatal(err)
	}
	return vf
}

// TestVectors checks against golden vectors generated by the Coinkite
// reference implementation (testdata/gen_vectors.py): Join must decode
// every series, and Split must reproduce the reference byte-for-byte
// whenever the encoding is Hex or Base32. Zlib series are decode-only
// golden: the reference's DEFLATE bitstream depends on zlib internals,
// so Split parity is asserted as a Join round-trip instead.
func TestVectors(t *testing.T) {
	vf := loadVectors(t)
	if got := versionChars[:]; !slices.Equal(got, vf.VersionChars) {
		t.Fatalf("capacity table mismatch: got %v want %v", got, vf.VersionChars)
	}
	for _, v := range vf.Vectors {
		t.Run(v.Name, func(t *testing.T) {
			data, err := hex.DecodeString(v.DataHex)
			if err != nil {
				t.Fatal(err)
			}
			ft, raw, err := Join(v.Parts)
			if err != nil {
				t.Fatalf("Join: %v", err)
			}
			if ft != v.FileType[0] || !bytes.Equal(raw, data) {
				t.Fatalf("Join = (%q, %d bytes), want (%q, %d bytes)", ft, len(raw), v.FileType[0], len(data))
			}

			opts := SplitOptions{
				MinVersion: v.Opts.MinVersion,
				MaxVersion: v.Opts.MaxVersion,
				MinSplit:   v.Opts.MinSplit,
				MaxSplit:   v.Opts.MaxSplit,
			}
			if v.EncodingOpt != "" {
				opts.Encoding = v.EncodingOpt[0]
			}
			s, err := Split(data, v.FileType[0], opts)
			if err != nil {
				t.Fatalf("Split: %v", err)
			}
			ft2, raw2, err := Join(s.Parts)
			if err != nil || ft2 != v.FileType[0] || !bytes.Equal(raw2, data) {
				t.Fatalf("Split round-trip: %v", err)
			}
			// Byte parity with the reference only applies when both
			// sides picked the same Hex or Base32 encoding: the
			// reference's DEFLATE bitstream depends on zlib internals
			// (lazy matching and dynamic Huffman beat our greedy fixed
			// blocks), so under auto/Zlib selection a Join round-trip
			// is the check, and the recorded options must still bound
			// the result or the option-pinning vectors pin nothing.
			checkOpts := func() {
				t.Helper()
				if o := v.Opts; (o.MinSplit > 0 && len(s.Parts) < o.MinSplit) ||
					(o.MaxSplit > 0 && len(s.Parts) > o.MaxSplit) ||
					(o.MinVersion > 0 && s.Version < o.MinVersion) ||
					(o.MaxVersion > 0 && s.Version > o.MaxVersion) {
					t.Fatalf("Split options ignored: version %d, %d parts, opts %+v",
						s.Version, len(s.Parts), o)
				}
			}
			if s.Encoding != v.Encoding[0] {
				if opts.Encoding == EncHex || opts.Encoding == EncBase32 {
					t.Fatalf("encoding changed under forced %q: got %q, want %q",
						opts.Encoding, s.Encoding, v.Encoding)
				}
				checkOpts()
				return
			}
			if s.Encoding == EncZlib {
				checkOpts()
				return
			}
			if s.Version != v.Version || !slices.Equal(s.Parts, v.Parts) {
				t.Fatalf("Split parity: got version %d, want %d (parts differ: %v)",
					s.Version, v.Version, !slices.Equal(s.Parts, v.Parts))
			}
		})
	}
}

func TestSplitJoinRoundTrip(t *testing.T) {
	rng := rand.New(rand.NewSource(1))
	for _, size := range []int{1, 2, 90, 91, 92, 500, 1000, 2144, 2145, 10000} {
		data := make([]byte, size)
		rng.Read(data)
		for _, enc := range []byte{0, EncHex, EncBase32, EncZlib} {
			s, err := Split(data, TypeBinary, SplitOptions{Encoding: enc})
			if err != nil {
				t.Fatalf("Split(%d bytes, enc %q): %v", size, enc, err)
			}
			// Scramble order and duplicate some parts: Join must cope.
			parts := slices.Clone(s.Parts)
			rng.Shuffle(len(parts), func(i, j int) { parts[i], parts[j] = parts[j], parts[i] })
			parts = append(parts, parts[rng.Intn(len(parts))])
			ft, raw, err := Join(parts)
			if err != nil {
				t.Fatalf("Join(%d bytes, enc %q): %v", size, s.Encoding, err)
			}
			if ft != TypeBinary || !bytes.Equal(raw, data) {
				t.Fatalf("round trip of %d bytes enc %q failed", size, s.Encoding)
			}
		}
	}
}

func TestSplitOptions(t *testing.T) {
	data := []byte(strings.Repeat("seedhammer ", 100))
	// Incompressible data, so MinSplit has parts to work with.
	rng := rand.New(rand.NewSource(3))
	raw := make([]byte, 1000)
	rng.Read(raw)
	s, err := Split(raw, TypeBinary, SplitOptions{Encoding: EncBase32, MinSplit: 3})
	if err != nil {
		t.Fatal(err)
	}
	if len(s.Parts) < 3 {
		t.Fatalf("MinSplit ignored: %d parts", len(s.Parts))
	}
	s, err = Split(data, TypeText, SplitOptions{MaxVersion: 10})
	if err != nil {
		t.Fatal(err)
	}
	if s.Version > 10 {
		t.Fatalf("MaxVersion ignored: version %d", s.Version)
	}
	for _, p := range s.Parts {
		if len(p) > versionChars[10-1] {
			t.Fatalf("part of %d chars exceeds version 10 capacity", len(p))
		}
	}
	if _, err := Split(data, TypeText, SplitOptions{MaxSplit: 1, MaxVersion: 1}); err == nil {
		t.Fatal("expected error for impossible bounds")
	}
	if _, err := Split(nil, TypeBinary, SplitOptions{}); err == nil {
		t.Fatal("expected error for empty data")
	}
	if _, err := Split(data, 'p', SplitOptions{}); err == nil {
		t.Fatal("expected error for lowercase file type")
	}
	if _, err := Split(data, TypeText, SplitOptions{Encoding: 'Q'}); err == nil {
		t.Fatal("expected error for unknown encoding")
	}
}

func TestJoinErrors(t *testing.T) {
	data := make([]byte, 3000)
	for i := range data {
		data[i] = byte(i)
	}
	s, err := Split(data, TypeBinary, SplitOptions{Encoding: EncHex, MaxVersion: 10})
	if err != nil {
		t.Fatal(err)
	}
	if len(s.Parts) < 3 {
		t.Fatalf("test needs a multi-part series, got %d", len(s.Parts))
	}
	good := s.Parts

	if _, _, err := Join(nil); err == nil {
		t.Fatal("no parts: expected error")
	}
	if _, _, err := Join(good[:len(good)-1]); err == nil {
		t.Fatal("missing part: expected error")
	}
	badpref := slices.Clone(good)
	badpref[0] = "XX" + badpref[0][2:]
	if _, _, err := Join(badpref); err == nil {
		t.Fatal("bad prefix: expected error")
	}
	short := slices.Clone(good)
	short[0] = "B$HP0"
	if _, _, err := Join(short); err == nil {
		t.Fatal("short part: expected error")
	}
	badenc := slices.Clone(good)
	badenc[0] = "B$XP" + badenc[0][4:]
	if _, _, err := Join(badenc); err == nil {
		t.Fatal("unknown encoding: expected error")
	}
	// Conflict: reheader the first part with a different file type.
	conflict := slices.Clone(good)
	conflict[0] = "B$HT" + conflict[0][4:]
	if _, _, err := Join(conflict); err == nil {
		t.Fatal("conflicting headers: expected error")
	}
	// Duplicate index, different content.
	dup := append(slices.Clone(good), good[0][:HeaderLen]+good[1][HeaderLen:])
	if _, _, err := Join(dup); err == nil {
		t.Fatal("differing duplicate: expected error")
	}
	// Odd-length hex body.
	odd := slices.Clone(good)
	odd[0] = good[0] + "A"
	if _, _, err := Join(odd); err == nil {
		t.Fatal("odd hex: expected error")
	}
	// Base32 length that cannot decode to whole bytes.
	if _, _, err := Join([]string{"B$2B0100ABC"}); err == nil {
		t.Fatal("bad base32 length: expected error")
	}
	// Zero total.
	if _, _, err := Join([]string{"B$HP0000"}); err == nil {
		t.Fatal("zero total: expected error")
	}
	// Index beyond total.
	if _, _, err := Join([]string{"B$HP0101ABCD"}); err == nil {
		t.Fatal("index beyond total: expected error")
	}
	// Corrupted zlib stream.
	if _, _, err := Join([]string{"B$ZB0100" + strings.Repeat("A", 8)}); err == nil {
		t.Fatal("bad zlib: expected error")
	}
}

func TestBase32(t *testing.T) {
	rng := rand.New(rand.NewSource(2))
	for size := 0; size < 64; size++ {
		data := make([]byte, size)
		rng.Read(data)
		enc := b32encode(data)
		if strings.ContainsRune(enc, '=') {
			t.Fatal("padding emitted")
		}
		dec, err := b32decode(enc)
		if err != nil || !bytes.Equal(dec, data) {
			t.Fatalf("round trip of %d bytes failed: %v", size, err)
		}
	}
	for _, s := range []string{"A", "AB", "ABC", "ABCDEF", "AB2"} {
		// Length residues 1, 3, 6 are impossible from whole bytes; 2, 5, 7 are valid.
		err := func() error { _, err := b32decode(s); return err }()
		switch len(s) % 8 {
		case 1, 3, 6:
			if err == nil {
				t.Fatalf("b32decode(%q): expected error", s)
			}
		default:
			if err != nil {
				t.Fatalf("b32decode(%q): %v", s, err)
			}
		}
	}
	if _, err := b32decode("ab"); err == nil {
		t.Fatal("lowercase accepted")
	}
	if _, err := b32decode("A!"); err == nil {
		t.Fatal("invalid character accepted")
	}
}

func TestDecoder(t *testing.T) {
	data := []byte(strings.Repeat("TheSeedHammer ", 500))
	s, err := Split(data, TypeText, SplitOptions{})
	if err != nil {
		t.Fatal(err)
	}
	var d Decoder
	if d.Complete() {
		t.Fatal("complete before any part")
	}
	if _, _, err := d.Result(); err == nil {
		t.Fatal("result before complete: expected error")
	}
	for i := len(s.Parts) - 1; i >= 0; i-- {
		if err := d.Add(s.Parts[i]); err != nil {
			t.Fatal(err)
		}
		if err := d.Add(s.Parts[i]); err != nil {
			t.Fatal("duplicate part must be a no-op:", err)
		}
	}
	have, total := d.Progress()
	if !d.Complete() || have != total || have != len(s.Parts) {
		t.Fatalf("progress = %d/%d, series has %d parts", have, total, len(s.Parts))
	}
	ft, raw, err := d.Result()
	if err != nil || ft != TypeText || !bytes.Equal(raw, data) {
		t.Fatalf("Result: %v", err)
	}

	// A part from another series must be rejected.
	var d2 Decoder
	if err := d2.Add(s.Parts[0]); err != nil {
		t.Fatal(err)
	}
	other, err := Split([]byte("unrelated"), TypeBinary, SplitOptions{})
	if err != nil {
		t.Fatal(err)
	}
	if err := d2.Add(other.Parts[0]); err == nil {
		t.Fatal("part from a different series accepted")
	}

	// The payload limit must hold. 3000 bytes of base32 in one part.
	big, err := Split(data, TypeText, SplitOptions{Encoding: EncBase32, MinSplit: 1})
	if err != nil {
		t.Fatal(err)
	}
	d3 := Decoder{Limit: 100}
	if err := d3.Add(big.Parts[0]); err == nil {
		t.Fatal("payload over limit accepted")
	}

	// A zlib bomb must trip the limit on decompression.
	bomb, err := Split(make([]byte, 2*1024*1024), TypeBinary, SplitOptions{Encoding: EncZlib})
	if err != nil {
		t.Fatal(err)
	}
	var d4 Decoder
	for _, p := range bomb.Parts {
		if err := d4.Add(p); err != nil {
			t.Fatal(err)
		}
	}
	if _, _, err := d4.Result(); err == nil {
		t.Fatal("decompression over limit accepted")
	}
}

func FuzzJoin(f *testing.F) {
	vf, err := os.ReadFile("testdata/vectors.json")
	if err == nil {
		var v vectorFile
		if json.Unmarshal(vf, &v) == nil {
			for _, vec := range v.Vectors {
				if len(vec.Parts) <= 4 {
					f.Add(strings.Join(vec.Parts, "\n"))
				}
			}
		}
	}
	f.Add("B$HP0100AB\nB$HP0100AB")
	f.Add("B$2B0100\n\nB$")
	f.Fuzz(func(t *testing.T, s string) {
		Join(strings.Split(s, "\n")) //nolint:errcheck // fuzzing for panics, not errors
	})
}

func FuzzDecoder(f *testing.F) {
	f.Add("B$2B0100AA\nB$HP0100AB\nB$2B0201MZXW6===\nB$2B0200MZXW6===")
	f.Fuzz(func(t *testing.T, s string) {
		var d Decoder
		for _, p := range strings.Split(s, "\n") {
			if err := d.Add(p); err != nil {
				break
			}
		}
		if d.Complete() {
			d.Result() //nolint:errcheck // fuzzing for panics, not errors
		}
	})
}

func FuzzSplitJoin(f *testing.F) {
	f.Add([]byte{0})
	f.Add([]byte("seedhammer"))
	f.Fuzz(func(t *testing.T, data []byte) {
		if len(data) == 0 || len(data) > 64*1024 {
			t.Skip("out of scope for the round trip fuzzer")
		}
		s, err := Split(data, TypeBinary, SplitOptions{})
		if err != nil {
			t.Fatal(err)
		}
		_, raw, err := Join(s.Parts)
		if err != nil {
			t.Fatal(err)
		}
		if !bytes.Equal(raw, data) {
			t.Fatal("round trip mismatch")
		}
	})
}

// TestJoinPartLengths: a non-runt part that lost a whole aligned
// group must fail the join instead of yielding silently corrupted
// output.
func TestJoinPartLengths(t *testing.T) {
	data := make([]byte, 88)
	rand.New(rand.NewSource(21)).Read(data)
	s, err := Split(data, TypeBinary, SplitOptions{Encoding: EncHex, MinVersion: 1, MaxVersion: 2})
	if err != nil {
		t.Fatal(err)
	}
	if len(s.Parts) < 2 {
		t.Fatalf("test needs several parts, got %d", len(s.Parts))
	}
	// Drop one byte (2 hex chars) from part 0's body.
	bad := append([]string(nil), s.Parts...)
	bad[0] = bad[0][:len(bad[0])-2]
	if _, _, err := Join(bad); err == nil {
		t.Fatal("join accepted a shortened non-runt part")
	}
	var d Decoder
	for _, p := range bad {
		if err := d.Add(p); err != nil {
			t.Fatal(err)
		}
	}
	if _, _, err := d.Result(); err == nil {
		t.Fatal("decoder accepted a shortened non-runt part")
	}
}

// TestDecoderAddRejectedPart: a part rejected for its body must not
// lock a fresh decoder to its series.
func TestDecoderAddRejectedPart(t *testing.T) {
	var d Decoder
	if err := d.Add("B$2B420011111"); err == nil {
		t.Fatal("invalid base32 body accepted")
	}
	if have, total := d.Progress(); have != 0 || total != 0 {
		t.Fatalf("rejected part committed the series: %d of %d", have, total)
	}
	s, err := Split([]byte("seedhammer"), TypeText, SplitOptions{})
	if err != nil {
		t.Fatal(err)
	}
	for _, p := range s.Parts {
		if err := d.Add(p); err != nil {
			t.Fatal(err)
		}
	}
	if _, data, err := d.Result(); err != nil || string(data) != "seedhammer" {
		t.Fatalf("decoder poisoned by the rejected part: %q, %v", data, err)
	}
}
