// Command emufixtures generates the Studio emulator's hotkey payloads:
// repeated-word seeds with valid checksums, and the multisig
// descriptors those same seeds cosign. The seeds are deliberately
// absurd (BACON BACON BACON …) so a demo plate is never mistaken for
// anyone's wallet, and deterministic so the descriptor a hotkey taps
// in is the one the seed hotkeys derive.
package main

import (
	"encoding/base64"
	"fmt"
	"os"
	"strings"

	"github.com/btcsuite/btcd/btcutil/v2/hdkeychain"
	"github.com/btcsuite/btcd/chaincfg/v2"
	"seedhammer.com/bip32"
	"seedhammer.com/bip380"
	"seedhammer.com/bip39"
)

// repeatSeed completes n-1 copies of word with the one word that makes
// the checksum valid, mirroring the device's own last-word flow. tail,
// if set, must be that word — the fixture's spelled-out expectation.
func repeatSeed(word string, n int, tail string) (bip39.Mnemonic, error) {
	w, ok := bip39.ClosestWord(strings.ToUpper(word))
	if !ok || bip39.LabelFor(w) != strings.ToUpper(word) {
		return nil, fmt.Errorf("%q is not a BIP39 word", word)
	}
	m := make(bip39.Mnemonic, n)
	for i := range m[:n-1] {
		m[i] = w
	}
	// A 12-word phrase leaves 7 free bits in its last word and a
	// 24-word one leaves 3, so many words complete either; tail names
	// the one this fixture wants, and without it the first is taken.
	if tail != "" {
		t, ok := bip39.ClosestWord(strings.ToUpper(tail))
		if !ok || bip39.LabelFor(t) != strings.ToUpper(tail) {
			return nil, fmt.Errorf("%q is not a BIP39 word", tail)
		}
		m[n-1] = t
		if !m.Valid() {
			return nil, fmt.Errorf("%s x%d + %s fails the checksum", word, n-1, tail)
		}
		return m, nil
	}
	for last := range bip39.Word(2048) {
		m[n-1] = last
		if m.Valid() {
			return m, nil
		}
	}
	return nil, fmt.Errorf("no checksum word completes %s x%d", word, n-1)
}

func words(m bip39.Mnemonic) string {
	out := make([]string, len(m))
	for i, w := range m {
		out[i] = strings.ToLower(bip39.LabelFor(w))
	}
	return strings.Join(out, " ")
}

func cosigner(m bip39.Mnemonic, path bip32.Path) (bip380.Key, error) {
	network := &chaincfg.MainNetParams
	mk, err := hdkeychain.NewMaster(bip39.MnemonicSeed(m, ""), network)
	if err != nil {
		return bip380.Key{}, err
	}
	pkey, err := mk.ECPubKey()
	if err != nil {
		return bip380.Key{}, err
	}
	xpub, err := bip32.Derive(mk, path)
	if err != nil {
		return bip380.Key{}, err
	}
	pub, err := xpub.ECPubKey()
	if err != nil {
		return bip380.Key{}, err
	}
	return bip380.Key{
		Network:           network,
		MasterFingerprint: bip32.Fingerprint(pkey),
		DerivationPath:    path,
		KeyData:           pub.SerializeCompressed(),
		ChainCode:         xpub.ChainCode(),
		ParentFingerprint: xpub.ParentFingerprint(),
	}, nil
}

func main() {
	if len(os.Args) < 2 || len(os.Args) > 3 {
		fmt.Fprintln(os.Stderr, "usage: emufixtures <out.js> [drawing.curves]")
		os.Exit(2)
	}
	drawing := ""
	if len(os.Args) == 3 {
		raw, err := os.ReadFile(os.Args[2])
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		// A v2 path payload is binary, so it travels as base64 and is
		// decoded back to the exact bytes a tag would carry.
		drawing = base64.StdEncoding.EncodeToString(raw)
		fmt.Fprintf(os.Stderr, "drawing    %d bytes -> %d base64\n", len(raw), len(drawing))
	}
	// The cosigner pool, in order. The quorums take prefixes of it, so
	// every descriptor shares the cosigners of the smaller ones.
	pool := []struct {
		word, tail string
		n          int
	}{
		{"bacon", "", 24},
		{"oil", "", 12},
		{"rug", "sad", 12},
		{"pizza", "", 12},
		{"salad", "", 12},
		{"olive", "", 12},
		{"lemon", "", 12},
	}
	path := bip380.P2WSH.DerivationPath()
	var keys []bip380.Key
	var seeds []string
	for _, p := range pool {
		m, err := repeatSeed(p.word, p.n, p.tail)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		k, err := cosigner(m, path)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		keys = append(keys, k)
		seeds = append(seeds, words(m))
		fmt.Fprintf(os.Stderr, "%-6s x%-2d -> %s (mfp %.8X)\n",
			p.word, p.n, words(m)[:min(40, len(words(m)))]+"…", k.MasterFingerprint)
	}

	desc := func(threshold, n int) string {
		d := &bip380.Descriptor{
			Script:    bip380.P2WSH,
			Type:      bip380.SortedMulti,
			Threshold: threshold,
			Keys:      keys[:n],
		}
		return d.Encode()
	}

	var b strings.Builder
	b.WriteString(`// Generated by cmd/emufixtures in the firmware repo; do not edit.
//
// The emulator's hotkey payloads: repeated-word seeds whose checksum
// word the device's own last-word arithmetic picks, and the multisig
// descriptors those seeds cosign — quorum n uses the first n seeds, so
// tapping seed 1 and then descriptor 3 shows the same wallet from both
// ends. Absurd on purpose: no one mistakes BACON BACON BACON for their
// own backup.
"use strict";
(function (root) {
  const F = {
`)
	fmt.Fprintf(&b, "    seed24: %q,\n", seeds[0])
	fmt.Fprintf(&b, "    seed12: %q,\n", seeds[1])
	fmt.Fprintf(&b, "    seedRug: %q,\n", seeds[2])
	fmt.Fprintf(&b, "    desc2of3: %q,\n", desc(2, 3))
	fmt.Fprintf(&b, "    desc3of5: %q,\n", desc(3, 5))
	fmt.Fprintf(&b, "    desc5of7: %q,\n", desc(5, 7))
	if drawing != "" {
		fmt.Fprintf(&b, "    drawingB64: %q,\n", drawing)
	}
	b.WriteString(`  };
  root.EmuFixtures = F;
})(typeof globalThis !== "undefined" ? globalThis : this);
`)
	if err := os.WriteFile(os.Args[1], []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", os.Args[1])
}
