// Command docs is the manuals' doctor. The screenshots and plate
// renders under docs/images are the firmware's own rendering,
// regenerated by a flag-gated test (go test ./gui -run TestUIShots);
// this command verifies the whole contract around them:
//
//   - Freshness: a regenerated set must match docs/images byte for
//     byte. A mismatch means a screen changed without its manual, or
//     an image was edited by hand.
//   - Integrity: every image a manual references exists, every image
//     on disk is referenced by a manual, and every reference carries
//     alt text.
//   - Prose: the mechanical subset of the house style — no em-dash
//     outside code, none of the flagged lexicon.
//
// -check (the default) reports findings and exits 1. -fix regenerates
// the images in place; prose and orphaned files always need a human.
package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
)

func main() {
	fix := flag.Bool("fix", false, "regenerate the images in place instead of failing on stale ones")
	flag.Parse()

	root, err := moduleRoot()
	if err != nil {
		fmt.Fprintln(os.Stderr, "docs:", err)
		os.Exit(2)
	}

	var findings []string
	fresh, err := freshness(root, *fix)
	if err != nil {
		fmt.Fprintln(os.Stderr, "docs:", err)
		os.Exit(2)
	}
	findings = append(findings, fresh...)

	prose, err := proseAndIntegrity(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "docs:", err)
		os.Exit(2)
	}
	findings = append(findings, prose...)

	for _, f := range findings {
		fmt.Fprintln(os.Stderr, f)
	}
	if len(findings) > 0 {
		fmt.Fprintf(os.Stderr, "docs: %d finding(s)\n", len(findings))
		os.Exit(1)
	}
}

// moduleRoot walks up from the working directory to the directory
// holding go.mod, so the doctor runs from anywhere inside the repo.
func moduleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod above the working directory")
		}
		dir = parent
	}
}

// proseFiles is the prose under the doctor's contract. Working notes
// (deliverables, .wiki) are deliberately outside it.
func proseFiles(root string) ([]string, error) {
	files, err := filepath.Glob(filepath.Join(root, "docs", "*.md"))
	if err != nil {
		return nil, err
	}
	files = append(files, filepath.Join(root, "README.md"))
	slices.Sort(files)
	return files, nil
}

// freshness regenerates the screenshot set into a scratch directory
// and compares it to docs/images. With fix set, generated files are
// written in place instead of reported; files the generator does not
// produce are always findings, never deleted.
func freshness(root string, fix bool) ([]string, error) {
	tmp, err := os.MkdirTemp("", "uishots")
	if err != nil {
		return nil, err
	}
	defer os.RemoveAll(tmp)

	cmd := exec.Command("go", "test", "./gui", "-run", "TestUIShots", "-uishots", tmp)
	cmd.Dir = root
	if out, err := cmd.CombinedOutput(); err != nil {
		return nil, fmt.Errorf("generating screenshots: %v\n%s", err, out)
	}

	imgDir := filepath.Join(root, "docs", "images")
	generated, err := pngSet(tmp)
	if err != nil {
		return nil, err
	}
	committed, err := pngSet(imgDir)
	if err != nil {
		return nil, err
	}

	var findings []string
	for _, name := range generated {
		want, err := os.ReadFile(filepath.Join(tmp, name))
		if err != nil {
			return nil, err
		}
		got, err := os.ReadFile(filepath.Join(imgDir, name))
		switch {
		case os.IsNotExist(err):
			if fix {
				if err := os.WriteFile(filepath.Join(imgDir, name), want, 0o644); err != nil {
					return nil, err
				}
				fmt.Fprintf(os.Stderr, "docs: wrote docs/images/%s\n", name)
				continue
			}
			findings = append(findings, fmt.Sprintf("docs/images/%s: missing (the generator produces it; run go run ./cmd/docs -fix)", name))
		case err != nil:
			return nil, err
		case !slices.Equal(want, got):
			if fix {
				if err := os.WriteFile(filepath.Join(imgDir, name), want, 0o644); err != nil {
					return nil, err
				}
				fmt.Fprintf(os.Stderr, "docs: rewrote docs/images/%s\n", name)
				continue
			}
			findings = append(findings, fmt.Sprintf("docs/images/%s: stale (a screen changed; run go run ./cmd/docs -fix)", name))
		}
	}
	for _, name := range committed {
		if !slices.Contains(generated, name) {
			findings = append(findings, fmt.Sprintf("docs/images/%s: not produced by the generator (delete it, or teach TestUIShots to)", name))
		}
	}
	return findings, nil
}

func pngSet(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var names []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".png") {
			names = append(names, e.Name())
		}
	}
	slices.Sort(names)
	return names, nil
}

// proseAndIntegrity scans every manual once: prose findings line by
// line, image references collected for the cross-file checks.
func proseAndIntegrity(root string) ([]string, error) {
	files, err := proseFiles(root)
	if err != nil {
		return nil, err
	}
	var findings []string
	referenced := make(map[string]bool)
	for _, path := range files {
		src, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return nil, err
		}
		pf, refs := scanProse(rel, src)
		findings = append(findings, pf...)
		for _, r := range refs {
			if r.alt == "" {
				findings = append(findings, fmt.Sprintf("%s:%d: image %s has no alt text", r.file, r.line, r.path))
			}
			if strings.Contains(r.path, "://") {
				continue
			}
			target := filepath.Join(root, filepath.Dir(r.file), r.path)
			if _, err := os.Stat(target); err != nil {
				findings = append(findings, fmt.Sprintf("%s:%d: image %s does not exist", r.file, r.line, r.path))
				continue
			}
			if imgRel, err := filepath.Rel(filepath.Join(root, "docs", "images"), target); err == nil && !strings.HasPrefix(imgRel, "..") {
				referenced[filepath.Base(imgRel)] = true
			}
		}
	}
	committed, err := pngSet(filepath.Join(root, "docs", "images"))
	if err != nil {
		return nil, err
	}
	for _, name := range committed {
		if !referenced[name] {
			findings = append(findings, fmt.Sprintf("docs/images/%s: referenced by no manual", name))
		}
	}
	return findings, nil
}
